openapi: "3.0.3"
info:
  title: "Delilah Restó"
  description: "API para la gestión de pedidos de un restaurante. Como cliente podrás registrarte,
  actualizar tu información, ver el listado de productos disponibles y realizar pedidos. Los administradores 
  del restaurante tienen la posibilidad de ver todos los pedidos y actualizarlos, así como también de crear 
  nuevos productos y eliminar otros existentes."
  version: "1.0.0"
  contact:
    name: "Aldana Daniela Casal"
    url: "https://github.com/aldanadc"
  license:
    name: "ISC"
servers:
  - url: "http://localhost:8080/api/1.0.0"
    description: "Servidor local"
paths:
  /login:
    post:
      summary: "Hacer login a cuenta de usuario"
      description: "Permite a un usuario existente hacer log in a su cuenta de acuerdo a sus datos de registro"
      responses:
        "200":
          $ref: "#/components/responses/200Success"
        "401":
          $ref: "#/components/responses/401NotAuthenticated"

  /register:
    post:
      summary: "Crear un nuevo usuario"
      description: "Permite crear un nuevo usuario con información proveniente de un formulario"
      requestBody:
        description: "Información del nuevo usuario"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              $ref: "#/components/examples/User"
      responses:
        "201":
          $ref: "#/components/responses/201Created"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /products:
    get:
      summary: "Retorna una lista con todos los productos disponibles"
      responses:
        "200":
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
              example:
                $ref: "#/components/examples/Products"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "500":
          $ref: "#/components/responses/500DefaultError"
    post:
      summary: "Crear un nuevo producto y añadirlo al menú"
      description: "Permite crear un nuevo producto de acuerdo a la estructura establecida y añadirlo al menú"
      requestBody:
        description: "Información del nuevo producto"
        required: true
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/Product"
      responses:
        "201": 
          $ref: "#/components/responses/201Created"
          description: "Información del producto creado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"

  /products/{product_id}:
    parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: string
    get:
      summary: "Retorna información detallada sobre un producto de acuerdo a su ID"
      responses:
        "200":
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:  
                $ref: "#/components/examples/Product"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"
    patch:
      summary: "Actualizar un producto existente"
      description: "Permite actualizar parcialmente la información del producto especificado de acuerdo a la estructura establecida"
      requestBody:
        description: "Información del producto a ser actualizada"
        required: true
        content:
          application/json:
              example:
                price: 399.99
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          description: "Información del producto luego de la actualización"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404":
          $ref: "#/components/responses/404NotFound"
    delete:
      summary: "Borrar un producto existente"
      description: "Permite borrar un producto existente en la base de datos"
      responses:
        "204":
          description: "Producto borrado exitosamente"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /users:
    get:
      summary: "Retorna información sobre todos los usuarios"
      description: "Retorna una lista de objetos con información de todos los usuarios registrados"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /users/{user_id}:
    parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
    get:
      summary: "Retorna información sobre un usuario"
      description: "Retorna una lista con un objeto de usuario conteniendo información del usuario especificado. Un usuario logueado no admin solo podrá acceder a su propia información"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                $ref: "#/components/examples/User"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"
    patch:
        summary: "Actualizar información de un usuario existente"
        description: "Permite a un usuario actualizar su propia información de acuerdo a la estructura establecida"
        requestBody:
          description: "Información actualizada del usuario"
          required: true
          content:
            application/json:
                example:
                  address: "10 Downing Street, London SW1A 2AB, UK"
                  phone_number: "+446565605898"
        responses:
          "200": 
            $ref: "#/components/responses/200Success"
          "400":
            $ref: "#/components/responses/400BadRequest"
          "401": 
            $ref: "#/components/responses/401NotAuthenticated"
          "403": 
            $ref: "#/components/responses/403NotAdmin"
          "500":
            $ref: "#/components/responses/500DefaultError"
    delete:
      summary: "Borrar un usuario existente"
      description: "Permite a cada usuario borrar su propio registro en la base de datos"
      responses:
        "204":
          description: "Usuario borrado exitosamente"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /users/{user_id}/favs:
    get:
      summary: "Retorna información sobre los productos favoritos de un usuario."
      description: "Devuelve una lista con un objeto conteniendo el id del usuario, su nombre de usuario y una lista de objetos de productos favoritos asociados al usuario. Solo el usuario en cuestión y un administrador pueden acceder a la información."
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
              example:  
                $ref: "#/components/examples/Products"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /orders:
    get:
      summary: "Retorna información sobre las órdenes del día"
      description: "Retorna una lista de objetos conteniendo información sobre todas las órdenes actuales del restaurante, incluyendo los productos asociados a cada orden"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404": 
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"
    post:
      summary: "Crear un nuevo pedido"
      description: "Crear y enviar una nueva orden al restaurante según lo especificado en el cuerpo de la petición"
      requestBody:
        description: "Detalles del pedido a enviar"
        required: true
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/Order"
              example:
                $ref: "#/components/examples/Order"
      responses:
        "201":
          $ref: "#/components/responses/201Created"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /orders/{order_id}:
    parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: integer
    get:
      summary: "Ver detalles y estado de un pedido"
      description: "Retorna un objeto con la información detallada de la orden especificada. Un usuario no admin solo puede acceder si la orden le pertenece"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
              example:
                $ref: "#/components/examples/Order"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "403": 
          $ref: "#/components/responses/403NotAdmin"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"
    patch:
      summary: "Actualizar estado de un pedido"
      description: "El usuario admin puede actualizar el estado de un pedido según corresponda"
      requestBody:
        description: "Nuevo estado de la orden"
        required: true
        content:
          application/json:
              schema:
                type: string
                enum:
                  - "Nuevo"
                  - "Confirmado"
                  - "Preparando"
                  - "Enviando"
                  - "Cancelado"
                  - "Entregado"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500DefaultError"
        
  /history:
    get:
      summary: "Retorna información histórica de órdenes recibidas"
      description: "Retorna una lista de objetos conteniendo información sobre todas las órdenes pasadas recibidas por el restaurante"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "404": 
          description: "No hay pedidos en el historial"
        "500":
          $ref: "#/components/responses/500DefaultError"

  /history/:date:
    get:
      summary: "Retorna información histórica de órdenes recibidas de acuerdo a su fecha"
      description: "Retorna una lista de objetos conteniendo información sobre órdenes pasadas recibidas 
      por el restaurante en la fecha especificada"
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
          example:
            "2021-04-05"
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "404": 
          description: "No hay pedidos registrados en la fecha especificada"
        "500":
          $ref: "#/components/responses/500DefaultError"
  
  
  /history/{user_id}:
    get:
      summary: "Retorna información histórica de órdenes realizadas por un usuario"
      description: "Retorna una lista de objetos conteniendo información sobre todas las órdenes pasadas 
      realizadas por el usuario especificado"
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        "200": 
          $ref: "#/components/responses/200Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        "401": 
          $ref: "#/components/responses/401NotAuthenticated"
        "404": 
          description: "No hay pedidos en el historial"
        "500":
          $ref: "#/components/responses/500DefaultError"
  
components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: number
        name:
          type: string
        description:
          type: string
        image:
          type: string
        ingredients:
          type: string
        price:
          type: number
        is_disabled:
          type: boolean
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    User: 
      type: object
      properties:
        user_id:
          type: number
        username:
          type: string
        full_name:
          type: string
        email:
          type: string
          format: email
        phone_number:
          type: string
        address: 
          type: string
        password:
          type: string
          format: password
        is_admin:
          type: boolean
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    OrderItem:
      type: object
      properties:
        product_id:
          type: number
        price:
          type: number
          format: float
        quantity:
          type: integer
    Order:
      type: object
      properties:
        order_id:
          type: integer
        order_status:
          type: string
          enum:
            - "Nuevo"
            - "Confirmado"
            - "Preparando"
            - "Enviando"
            - "Cancelado"
            - "Entregado"
        order_date:
          type: string
          format: date-time
        products:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem" 
        total: 
          type: number
          format: float
        payment_method:
          type: string
        delivery_address:
          type: string
        customer_name:
          type: string
        customer_email:
          type: string
        customer_phone:
          type: string
    Orders:
      type: array
      items:
        $ref: "#/components/schemas/Order"
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
  responses:
    200Success:
      description: "Operación exitosa"
    201Created:
      description: "Recurso creado correctamente"
    400BadRequest:
      description: "La información enviada es incorrecta o inválida para realizar la operación"
    401NotAuthenticated:
      description: "Credenciales inválidas. Autenticación necesaria para realizar la operación"
    403NotAdmin:
      description: "El usuario no es administrador y no está autorizado a realizar la operación"
    404NotFound:
      description: "El recurso especificado no existe"
    500DefaultError:
      description: "Error imprevisto, no se pudo completar la acción solicitada"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  examples:
    Product:
      value:
        name: "Tacos al pastor"
        description: "Delicioso taco de carne de cerdo y ternera marinada, vegetales y condimentos, acompañado
        de una deliciosa salsa picante"
        ingredients:
          - "carne de cerdo y ternera"
          - "chile picante"
          - "ajo"
          - "cebolla"
          - "cilantro"
          - "comino"
          - "sal"
          - "piña"
          - "tortilla de maíz"
        price: 349.99
    Products:
      value:
        - name: "Tacos al pastor"
          description: "Delicioso taco de carne de cerdo y ternera marinada, vegetales y condimentos, acompañado
          de una deliciosa salsa picante"
          ingredients:
            - "carne de cerdo y ternera"
            - "chile picante"
            - "ajo"
            - "cebolla"
            - "cilantro"
            - "comino"
            - "sal"
            - "piña"
            - "tortilla de maíz"
          price: 349.99
        - name: "Carnitas burrito"
          description: "Nuestro burrito estrella, preparado con carne de cerdo adobada, vegetales, porotos negros 
          y arroz, acompañado de una deliciosa salsa picante"
          ingredients:
            - "carne de cerdo adobada"
            - "arroz blanco"
            - "porotos negros"
            - "cebolla"
            - "tomate"
            - "lechuga"
            - "cilantro"
            - "chile picante"
            - "palta"
            - "sal"
            - "tortilla de maíz"
          price: 379.99
    User:
      value:
        username: "queen_freddie"
        full_name: "Freddie Mercury"
        email: "freddiemercury@gmail.com"
        phone_number: "+447712345678"
        address: "1 Logan Pl, Kensington, London, W8 6DE, UK"
        password: "Eeeeeeoo123"
        is_admin: false
    Order:
      value:
        order_id: 75
        order_status: "Nuevo"
        order_time: "2021-05-05T23:23:59.000Z"
        products:
          - product: "Tacos al pastor"
            price: 349.99
            quantity: 1
        total: 349.99
        payment_method: "Efectivo"
        delivery_address: "1 Logan Pl, Kensington, London, W8 6DE, UK"
        customer_name: "Freddie Mercury"
        customer_email: "freddiemercury@gmail.com"
        customer_phone: "+447712345678"
